### ISSUE TITLE
build: contents of src/CMakeLists.txt are ignored

### ISSUE THREAD

**Issue by roehling** [catkin/catkin_tools#140] opened 2015-01-27 08:31 UTC
I noticed that `catkin build` will silently ignore `src/CMakeLists.txt`. I use that file to call `catkin_lint` and set up compiler options (so I don't have to clutter my packages with them); I know it's a non-standard setup, but it is very useful and much less cumbersome than passing various -DCMAKE_XXX options to the `catkin_make`/`catkin build` calls.

**Comment by wjwwood** [comment] 2015-01-27 18:46
First off, I would not replace the top level `CMakeLists.txt` at all, because updates to it via catkin upgrades will not get put in.

Either way, this file is also ignored by `catkin_make_isolated` and it only ever used by `catkin_make`. I do not believe it makes sense for either `catkin_make_isolated` nor `catkin build` to parse this file. It's existence is a matter of implementation detail for `catkin_make`, and I would not rely on its existence.

----

As for running `catkin_lint`:

I would also not add the invocation of `catkin_lint` in the top level `CMakeLists.txt` file since anyone who gets your packages from source will not get the benefit of the `catkin_lint ` check. So, for example you would not get this in a CI run of your package when testing the validity of a pull request. I believe you should have invocation of `catkin_lint` be triggered as a Python unit test, e.g. this is how I check PEP8 compliance on this package:

https://github.com/catkin/catkin_tools/blob/master/tests/test_code_format.py

It's not clutter if it improves the package, and you can hide 90% of it with CMake infrastructure and the rest is boilerplate.

The other option, if you don't want each package to test it's own CMake as an automated test, is to extend the build tools directly. You were extending `catkin_make` sort of indirectly by replacing the default top level `CMakeLists.txt`. To accomplish the same thing with `catkin_make_isolated` or `catkin_tools` you'll need to extend them directly. `catkin_tools` was designed with exactly this in mind:

http://catkin-tools.readthedocs.org/en/latest/development/extending_the_catkin_command.html

----

As for adding persistent CMake/Make arguments:

This is handled by `catkin config`, see:

- `catkin config -h`
- http://catkin-tools.readthedocs.org/en/latest/verbs/catkin_config.html

In both cases see the `Build Options:` section of the help.

You could also make use of the CMake toolchain file pattern: http://www.cmake.org/cmake/help/v3.0/manual/cmake-toolchains.7.html

**Comment by wjwwood** [comment] 2015-01-27 18:47
I'm gonna close this for now, but please comment if you think is should be kept open.

**Closed by wjwwood** 2015-01-27 18:47 UTC

**Comment by roehling** [comment] 2015-01-28 09:42
Thanks for taking the time and giving such a detailed answer. The `catkin config` commit totally escaped my notice; I merely checked the `build` verb for options.

I will look into the issue of how to invoke `catkin_lint` and get back to you if I have any questions.

By the way, I did not replace the top level file completely; I symlinked it as `toplevel.cmake` and included it at the end of my custom  `CMakeLists.txt`. I still think it is a good way to introduce customized workspace settings (I few ROS versions earlier, there even has been an explicit include() statement in the top level file to do precisely that), but I also concede that the `catkin_tools` design has its advantages when it comes to robust builds and package unit testing.

**Comment by jbohren** [comment] 2015-01-28 13:17
Maybe there should be an option like:

```
catkin config --cmake-file src/my_config_repo/SomeOptions.cmake
```

This could support more advanced use cases where a bunch of options need to be set across multiple packages.

**Comment by jack-oquin** [comment] 2015-01-28 16:37
I still prefer that each package be self-contained and set its own CMake options, as needed. Putting custom build information at the workspace level would probably lead people to commit packages without important options.

If a project has lots of packages with complicated common options, it can provide its own ``<build_depend>`` package for setting them.

**Comment by jbohren** [comment] 2015-01-28 16:45
> I still prefer that each package be self-contained and set its own CMake options, as needed. Putting custom build information at the workspace level would probably lead people to commit packages without important options.

But some packages have optional *variant* flags. On my simulation machine, I set `-DENABLE_CORBA=On -DCORBA_IMPLEMENTATION=OMNIORB` for using the Orocos remote corba interface. On one of my teleop machines that uses stereo RViz I have other options set which enable building RViz and Ogre with stereo support. On one perception machine, I build something with CUDA support, and when I run the same code on my laptop, I disable it.

> If a project has lots of packages with complicated common options, it can provide its own <build_depend> package for setting them.

This would work when abusing `catkin_make` but not `catkin_make_isolated` or `catkin build`.

You're right though, we wouldn't want people abusing it.

So what we _should_ have is:

```
catkin config --yaml > my_special_config.yaml
```

Paired with:

```
catkin config --yaml < my_special_config.yaml
```
