### ISSUE TITLE
Unable to source devel/setup.bash after generating with catkin build

### ISSUE THREAD

**Issue by aa-tom** [catkin/catkin_tools#681] opened 2021-07-15 14:23 UTC
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: Linux aa-006 5.8.0-59-generic # 66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

* Python Version: 3.8.10
* Version of catkin_tools: 0.5.0
* ROS Distro: noetic

### Build / Run Issue

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [X] Works with `catkin_make`
* [X] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [ ] I did  not `read this`

### Expected Behavior

As with catkin_make, I should be able to source the generated deve/setup.bash file

[//]: # (Please describe what you expected or think should happen.)

### Actual Behavior

[//]: # (Please describe what actually happens.)

The bash file cannot be found, despite it being listed as existing

```
rob@aa-006:~/projects/aa-ros$ ls /home/rob/projects/aa-ros/internal/devel/ 
cmake.lock  env.sh  include  lib  local_setup.bash  local_setup.sh  local_setup.zsh  setup.bash  setup.sh  _setup_util.py  setup.zsh  share
rob@aa-006:~/projects/aa-ros$ source /home/rob/projects/aa-ros/internal/devel/setup.bash 
bash: /home/rob/projects/aa-ros/internal/devel/setup.bash: No such file or directory
```

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)

### Steps to Reproduce the Issue

[//]: # (Please give a series of command-line commands which cause the problem.)
[//]: # (Include a checkout URI for the workspace so that we can reproduce the issue.)
[//]: # (If we can't reproduce it on our own machines, we can't fix it!)

```bash

- cd $PACKAGE_PATH
- catkin build
- source $PACKAGE_PATH/devel/setup.bash
```

**Comment by aa-tom** [comment] 2021-07-15 16:29
Note: if I run `catkin build --install` instead, I can use source install/setup.bash, however this leads to issues running my tests as certain files aren't present in the install space

**Comment by timonegk** [comment] 2021-07-15 17:09
Hi, thanks for the bug report. The issue might be a broken symlink, could you post the output of `file /home/rob/projects/aa-ros/internal/devel/setup.bash`?
Also, does the issue still occur after you run `catkin clean` and `catkin build` again?

**Comment by aa-tom** [comment] 2021-07-15 18:11
Thanks for the quick response. Cleaning and rebuilding doesn't fix the issue unfortunately. Looks like it is a broken symlink:

```
rob@aa-006:~/projects/aa-ros$ file /home/rob/projects/aa-ros/internal/devel/setup.bash 
/home/rob/projects/aa-ros/internal/devel/setup.bash: broken symbolic link to /home/rob/checkout/internal/devel/.private/catkin_tools_prebuild/setup.bash
rob@aa-006:~/projects/aa-ros$ file /home/rob/projects/aa-ros/internal/devel/.private/catkin_tools_prebuild/setup.bash 
/home/rob/projects/aa-ros/internal/devel/.private/catkin_tools_prebuild/setup.bash: Bourne-Again shell script, ASCII text executable
```

Suppose I could try sourcing the .private copy as a workaround?

**Comment by timonegk** [comment] 2021-07-15 19:06
The issue seems to be that `/home/rob/projects/aa-ros/internal` is/was/is detected as a symlink to `/home/rob/checkout/internal`. Did you have such a symlinked setup and if that's the case could you tell me the details of the setup?
But yes, sourcing the .private copy should work, but there could emerge other problems later on if there is some symlinking problem that is not handled well by catkin tools.

**Comment by aa-tom** [comment] 2021-07-15 19:21
I'm not too clear on the symlink details to be honest. We have a docker container set up to contain the built code which _is_ present at `/home/rob/checkout/`. I've just checked and sourcing from `/home/rob/checkout/` within the container does still work. There's never a `checkout` directory left by the build outside of the container, however, sourcing from `/home/rob/projects/aa-ros/internal` outside of docker does work when building through `catkin_make`. It's just `catkin build` where the issue appears.

Sourcing from within the docker container or using the .private copy solves the immediate issue, although I then run into the original problem I was having which was failing tests / unfound packages as a result of the migration (one I was hoping would be fixed by sourcing).

Details of that issue are here: https://github.com/ros/catkin/issues/1148. Not sure if we should close this issue or continue discussion here since the linked issue is related and probably belongs in the `catkin_tools` repo rather than the `catkin` one ?

**Comment by timonegk** [comment] 2021-07-16 07:51
Okay, so you are building inside of the container and using the built code outside of it? That would be the cause as catkin_tools does not expect the path of your devel space to change. I don't see an immediate reason for having the links to `.private` absolute, relative links should also work, even though it might be some effort to change at all places, I would have to look into that.

The linking is done by catkin for the so-called [linked devel space](https://catkin-tools.readthedocs.io/en/latest/advanced/linked_develspace.html) that combines advantages of the merged and isolated devel spaces possible with `catkin_make` and `catkin_make_isolated`. You can replicate the normal `catkin_make` behaviour by running `catkin config --merge-devel`. That should solve your problem.

**Comment by aa-tom** [comment] 2021-07-16 09:49
Ah yeah the built code does also run in a docker container (which works fine). All the work done outside was just me doing manual tests -- should probably have been doing them from the container shell!

Managed to resolve the test failures, too. The issue was that we're building two workspaces -- external and internal -- with dependencies between the latter to the former. Had to change the build script to build the external dependencies before the internal ones. Still a little unsure how that was working with catkin_make though...

**Closed** 2021-07-16 11:52 UTC

**Comment by timonegk** [comment] 2021-07-16 12:20
You're welcome – I'm glad I could help!
