### ISSUE TITLE
run_tests without compiler output?

### ISSUE THREAD

**Issue by HWiese1980** [catkin/catkin_tools#490] opened 2017-10-19 08:21 UTC
I'm trying to make `catkin` run my unit tests. It works but there's a lot of output from `catkin_make` that I don't need. The default alias for `catkin run_tests` contains the `--verbose` parameter for `catkin build` which appears to be necessary in order to get the test result output. But it also outputs all those compiler and linker info stuff that I don't need. 

Is there a way to get only the `run_tests` output (see below) while suppressing the `make` output?

    -- run_tests.py: execute commands
      /home/.../test --gtest_output=xml:/home/.../gtest-test.xml
    [==========] Running 1 test from 1 test case.
    [----------] Global test environment set-up.
    [----------] 1 test from TestSuite
    [ RUN      ] TestSuite.testCase1
    /home/.../test/utest.cpp:5: Failure
    Failed
    [  FAILED  ] TestSuite.testCase1 (0 ms)
    [----------] 1 test from TestSuite (0 ms total)

    [----------] Global test environment tear-down
    [==========] 1 test from 1 test case ran. (0 ms total)
    [  PASSED  ] 0 tests.
    [  FAILED  ] 1 test, listed below:
    [  FAILED  ] TestSuite.testCase1

     1 FAILED TEST

**Comment by wjwwood** [comment] 2017-10-19 15:55
Perhaps a duplicate of https://github.com/catkin/catkin_tools/issues/405?

(closing assuming that is so, can reopen if needed)

**Closed by wjwwood** 2017-10-19 15:55 UTC

**Comment by HWiese1980** [comment] 2017-10-20 07:36
Yepp, duplicate. Thanks for the link!
