### ISSUE TITLE
did not exist immediately  when smaller limit-status-rate

### ISSUE THREAD

**Issue by k-okada** [catkin/catkin_tools#337] opened 2016-04-19 07:29 UTC
when we set very small number on the limit-status-rate, the catkin build did not return until the system shows next status info, for example;
```
catkin build --limit-status-rate 0.01
```
will wait for 100 sec, even if you compile a single empty package.

**Comment by jbohren** [comment] 2016-04-19 11:27
I assume this is with 0.4.0?

**Comment by k-okada** [comment] 2016-04-19 11:37
Yes

--
◉ Kei Okada

2016/04/19 20:27、Jonathan Bohren <notifications@github.com> のメッセージ:

**Comment by jbohren** [comment] 2016-04-19 17:24
@k-okada This should be fixed with #344.

**Comment by jbohren** [comment] 2016-04-20 15:00
@k-okada I reopened this because #344 introduced a regression.

**Closed** 2016-04-20 21:39 UTC
Labels: bug
