### ISSUE TITLE
catkin clean PKGNAME not working

### ISSUE THREAD

**Issue by samuelba** [catkin/catkin_tools#343] opened 2016-04-19 15:12 UTC
### System Info

* Operating System: `Linux sam-t440p 3.16.0-70-generic #90~14.04.1-Ubuntu SMP Wed Apr 6 22:56:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: `Python 2.7.6`
* Version of catkin_tools: `catkin_tools 0.4.0 (C) 2014-2016 Open Source Robotics Foundation
catkin_tools is released under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
---
Using Python 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]`
* ROS Distro: `indigo`

### Expected Behavior

e.g. running `catkin clean any_msgs` should remove the package from the `devel` and `build` folder.

### Actual Behavior

The package is still in the `devel` and `build` folder and isn't build new when running `catkin build any_msgs`. The output is:

```
[clean] Nothing to be cleaned for profile:  'default'
```

however, if I run `catkin clean any_msgs --dry-run` the output is:

```
Starting  >>> any_msgs             
Finished  <<< any_msgs              [ 0.0 seconds ]
[clean] Summary: All 1 packages succeeded!
[clean]   Ignored:   None.
[clean]   Warnings:  None.
[clean]   Abandoned: None.
[clean]   Failed:    None.
[clean] Runtime: 0.7 seconds total.
[clean] Note: Parts of the workspace have been cleaned which will necessitate re-configuring CMake on the next build.
```

which I think should be the output for `catkin clean any_msgs` too.

My `catkin config` looks like that:

```
------------------------------------------------------------------------------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/indigo
Workspace:                   /home/sam/catkin_ws
------------------------------------------------------------------------------------------------------------------------------------------------
Source Space:       [exists] /home/sam/catkin_ws/src
Log Space:          [exists] /home/sam/catkin_ws/logs
Build Space:        [exists] /home/sam/catkin_ws/build
Devel Space:        [exists] /home/sam/catkin_ws/devel
Install Space:      [unused] /home/sam/catkin_ws/install
DESTDIR:            [unused] None
------------------------------------------------------------------------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
------------------------------------------------------------------------------------------------------------------------------------------------
Additional CMake Args:       -DUSE_TASK_LOCOCRAWLING_ROS=ON -DUSE_TASK_LOCODEMO_ROS=ON -DUSE_TASK_LOCOFREEGAIT_ROS=ON -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
------------------------------------------------------------------------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
------------------------------------------------------------------------------------------------------------------------------------------------
Workspace configuration appears valid.
------------------------------------------------------------------------------------------------------------------------------------------------
```

Do I do something wrong? Or is this a bug?

**Comment by jbohren** [comment] 2016-04-19 15:32
@samuelba Thanks for the detailed report! It's a bug caused by an extra safety check that was added recently. It's already been fixed in master with: https://github.com/catkin/catkin_tools/pull/340

**Closed by jbohren** 2016-04-19 15:32 UTC
Labels: duplicate
