### ISSUE TITLE
overlays problem

### ISSUE THREAD

**Issue by bricerebsamen** [catkin/catkin_tools#160] opened 2015-03-13 00:24 UTC
I am porting my code to tf2 and working on a fix on tf2 at the same time.
So I have a workspace with all my packages and a copy of the geometry_experimental repo.
My build fails because my packages are built against the stock version of tf2_ros and not the overlay.

The package that fails does not have an explicit dependency to tf2_ros but depends on it implicitly (i.e. brought over by other dependencies).

It seems however that if I first build the workspace, then source the setup.bash, then clean and rebuild, the problem is resolved.

**Comment by dirk-thomas** [comment] 2015-03-13 00:27
I think this is a duplicate of #30.

**Comment by wjwwood** [comment] 2015-03-13 00:28
I agree, @bricerebsamen if you concur, could you close this issue and comment there?

**Closed** 2015-03-13 00:43 UTC
