### ISSUE TITLE
problem of source devel/setup.bash generated by `catkin build` with --install configuration

### ISSUE THREAD

**Issue by yuzhangbit** [catkin/catkin_tools#441] opened 2017-03-03 22:20 UTC
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: Linux precision 4.4.0-64-generic #85~14.04.1-Ubuntu SMP Mon Feb 20 12:10:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 2.7.6
* Version of catkin_tools: catkin_tools 0.4.4 (C) 2014-2017 Open Source Robotics Foundation
catkin_tools is released under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
Using Python 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

* ROS Distro: indigo

### Build / Run Issue

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [ ] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge`
* [x] Works with `catkin build`
* [x] Works with `catkin build -p1`
* [ ] I did  not `read this`

### Expected Behavior

After `catkin build` and `source catkin_ws/devel/setup.bash`, I should be able to navigate to the target package folder using `roscd target_package` .

### Actual Behavior

I configure the catkin workspace with following commands
```bash
cd /path/to/catkin_ws
catkin init
catkin config --extend /opt/ros/indigo
catkin config --install
catkin build
source /path/to/catkin_ws/devel/setup.bash
roscd target_package
```
The output is 
```
roscd: No such package/stack 'target_package'
```
The target_package exits in `catkin_ws/src` folder and compiles fine.

If I `source catkin_ws/install/setup.bash`, I can use `roscd target_package` to find the folder in `catkin_ws/install` folder.

If I don't configure catkin_ws with `catkin config --install`, I can use `roscd target_package` as expected after `catkin build` and `source catkin_ws/devel/setup.bash`. 

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)

### Steps to Reproduce the Issue

The reproduce commands:
```bash
cd /path/to/catkin_ws
catkin init
catkin config --extend /opt/ros/indigo
catkin config --install
catkin build
source /path/to/catkin_ws/devel/setup.bash
roscd target_package
```
[//]: # (Include a checkout URI for the workspace so that we can reproduce the issue.)
[//]: # (If we can't reproduce it on our own machines, we can't fix it!)

**Comment by NikolausDemmel** [comment] 2017-03-03 22:33
Shouldn't you source the install space's setup.vash if you configure with --install?

**Comment by yuzhangbit** [comment] 2017-03-03 22:50
@NikolausDemmel  I don't know.  I should at least be able to rewrite all the ros environment variables  with `source catkin_ws/devel/setup.bash`, right?

**Comment by NikolausDemmel** [comment] 2017-03-04 00:04
I would say no, but I'm not sure. I feel like this has been discussed before, maybe you can have a look in the existing issues (also closed).

**Comment by wjwwood** [comment] 2017-03-04 00:26
I think this is (effectively) a duplicate of #404, to which there was a proposed pull request that was supposed to fix it, but as I comment there I don't think this is a use case we want to support:

https://github.com/catkin/catkin_tools/pull/403#issuecomment-271052265

It makes much more sense to use the `source catkin_ws/install/setup.bash` when you're using the `catkin config --install` option.

**Comment by yuzhangbit** [comment] 2017-03-06 16:09
Thank you! @NikolausDemmel @wjwwood

**Comment by wjwwood** [comment] 2017-03-06 21:26
@yuzhangbit I'm going to close this, but feel free to continue discussion on the linked issue: https://github.com/catkin/catkin_tools/pull/403#issuecomment-271052265

**Closed by wjwwood** 2017-03-06 21:26 UTC
