### ISSUE TITLE
build: -j and -p defaults

### ISSUE THREAD

**Issue by NikolausDemmel** [catkin/catkin_tools#188] opened 2015-04-04 18:22 UTC
With the jobserver implementation merged, I suggest to change the default of the `-p` argument from "cpu count" to "value of `-j` argument". 

If you pass neither, both will be "cpu count" as they are currently, making for a reasonable default.

I would assert, that most of the time when passing `-j` explicitly, you would also want to pass `-p` with the same value. By changing the default as suggested, `-j` would be more of DWIM.

One could suggest to make it the other way round, i.e. have `-j` default ot the value of `-p`, but IMHO there is a valid use case for wanting to `-p1` and still have `-j` default to cpu count. Also, `-j` is more of a standard for people who know `make` and `catkin_make`.

Thoughts?

**Comment by jack-oquin** [comment] 2015-04-04 20:32
Makes sense to me, as a naive user with little understanding of these details.

**Comment by jbohren** [comment] 2015-04-05 23:12
+1

**Comment by wjwwood** [comment] 2015-04-06 18:52
This is effectively what is happening since the start of a build is blocked on a `with job_server` context:

https://github.com/catkin/catkin_tools/blob/master/catkin_tools/verbs/catkin_build/executor.py#L127

I thought this might be unintended, because it seems like it would also prevent `cmake` from running if there are no job tokens available, however, it's still not entirely clear to me how the job server enter and exit are supposed to work along with the `make` subprocesses. Ultimately, I decided to merge based on the acceptance testing I did.

The observable result is that the jobs which are listed as "building" (taking up one of the `-p` slots) can actually be doing nothing and waiting on the job server to give them time with a job server token. So maybe @jbohren can shed some light on why the `job_server` context is there and what the intended behavior is supposed to be.

With all of that being said I think @NikolausDemmel's suggestion actually makes sense and I would take a pull request which changed this (along with any documentation that's needed to convey this behavior).

**Comment by wjwwood** [comment] 2015-04-07 00:12
@NikolausDemmel given that this is run on a 4 core machine:

```
% catkin build --no-jobserver -j1
```

What should be the default value of `-p`?

**Comment by jbohren** [comment] 2015-04-07 01:40
I was thinking that if e want to implement a more sophisticated policy that
the `p` value should, in general, be less than or equal to the `j` value.

**Comment by NikolausDemmel** [comment] 2015-04-08 22:51
> I was thinking that if e want to implement a more sophisticated policy that
the `p` value should, in general, be less than or equal to the `j` value.

Do you mean simply setting `p = min(p, j)` (if the jobserver is in use)? Seems reasonable as a policy and we don't have to change default values.

**Comment by wjwwood** [comment] 2015-04-21 19:07
I had to add f797eb6 to prevent jobs which tried to start building after `ctrl-c`.

I'm not convinced that the current implementation of the job server is what we want. It produces results that work in most cases to achieve the desired goal, but there is some strangeness with the design that is related to this topic. Like I said before I think `-j` is essentially controlling `-p` since an executor cannot operate until there is a job token available.

I think the job server happens to works ok right now so that's why I merged and released it, but I'd still like something like a "theory of operation" from @jbohren so we could all be on the same page as to what we think it is doing and what it actually is doing and move forward from there.

**Comment by jbohren** [comment] 2015-04-21 19:47
> I think the job server happens to works ok right now so that's why I merged and released it, but I'd still like something like a "theory of operation" from @jbohren so we could all be on the same page as to what we think it is doing and what it actually is doing and move forward from there.

It doesn't try to do anything too intelligent, just does what it says here:

https://github.com/catkin/catkin_tools/blob/master/docs/verbs/catkin_build.rst#controlling-the-number-of-build-jobs

**Comment by wjwwood** [comment] 2015-04-21 20:31
I was referring to the implementation on the behavior.

For example, It's not clear to me how you could have `-p 6 -j4` and not just stall two of the `-p` jobs (including running `cmake`, not just the `make` part of those jobs).

It's also not clear to me how `-p2 -j4` would result in to two jobs with two instances of `make` running in the equivalent to `make -j2`.

I would appreciate an overview of how that stuff is supposed to work.

**Comment by jbohren** [comment] 2015-04-21 20:38
> For example, It's not clear to me how you could have -p 6 -j4 and not just stall two of the -p jobs (including running cmake, not just the make part of those jobs).

That's because it _would_ stall the two packages. It wouldn't stall the CMake part, but it would block the Make part, effectively stalling the package.

> It's also not clear to me how -p2 -j4 would result in to two jobs with two instances of make running in the equivalent to make -j2.

The jobs are distributed on a first-come, first-serve basis. There's no equal balancing or anything across the packages. So `-p2 -j4` isn't exactly the same was calling `make -j2` simultaneously. What's happening in this case is that there are 4 total jobs and the two packages will try to grab as many of them as they can utilize as they're available. 

It all follows the behavior described here: http://make.mad-scientist.net/papers/jobserver-implementation/

**Comment by wjwwood** [comment] 2015-04-21 21:42
> It wouldn't stall the CMake part, but it would block the Make part, effectively stalling the package.

Based on my testing I don't think that I observed that. I think that this line:

https://github.com/catkin/catkin_tools/blob/master/catkin_tools/verbs/catkin_build/executor.py#L128

Will block the start of new jobs (where job means `cmake` + `make` ... etc.), which is why if you ctrl-c while there is load on the system (building more than one package that takes time to build), it stops the current jobs, but jobs that were waiting then start. Then you have to wait for them to finish or send ctrl-c again. That's what lead me to introduce: https://github.com/catkin/catkin_tools/commit/f797eb68170875b41522e447fdff233983f1bdb3

> The jobs are distributed on a first-come, first-serve basis. There's no equal balancing or anything across the packages. So -p2 -j4 isn't exactly the same was calling make -j2 simultaneously. What's happening in this case is that there are 4 total jobs and the two packages will try to grab as many of them as they can utilize as they're available.

> It all follows the behavior described here: http://make.mad-scientist.net/papers/jobserver-implementation/

But your documentation states:

> By default, these jobs options aren't passed to the underlying make command.

Which lead me to believe that the underlying `make` jobs do not take tokens from the internal job server, but instead the `with job_server():` line linked above was take and returning job tokens. Even if the leaf `make` jobs somehow use the internal job server, it seems to me that the `with job_server():` will consume one of the tokens per job anyways.

Maybe at the root of this I don't understand the purpose or function of the `with job_server():` line or how it interacts with the leaf `make` processes. Could you expand on that mechanism?

**Comment by jbohren** [comment] 2015-04-21 22:34
> But your documentation states:

>> By default, these jobs options aren't passed to the underlying make command.

>Which lead me to believe that the underlying make jobs do not take tokens from the internal job server, but instead the with job_server(): line linked above was taking and returning job tokens. Even if the leaf make jobs somehow use the internal job server, it seems to me that the with job_server(): will consume one of the tokens per job anyways.

And taken out of context, I can understand why it would lead you to believe that. But the whole paragraph reads:

From [controlling-the-number-of-build-jobs](https://github.com/catkin/catkin_tools/blob/master/docs/verbs/catkin_build.rst#controlling-the-number-of-build-jobs):
> You can control the maximum number of packages allowed to build in parallel by using the -p or --parallel-packages option and you can change the number of make jobs available with the -j or --jobs option.
>
> By default, these jobs options aren't passed to the underlying make command. To disable the jobserver, you can use the --no-jobserver option, and you can pass flags directly to make with the --make-args option.

In the line that you quoted "these jobs" refers to the `-p`, `--parallel-packages`, `-j`, and `--jobs` options mentioned in the previous pragraph. These options aren't passed unless you disable the jobserver with `--no-jobserver`. By default, the options passed to `make` when using the jobserver are those generated by [`make_jobserver.jobserver_arguments()`](https://github.com/catkin/catkin_tools/blob/master/catkin_tools/make_jobserver.py#L257-265).

Like I said above, this is implemented according to the behavior described here: http://make.mad-scientist.net/papers/jobserver-implementation/

Specifically, from the "Final Result" section:
> In the brief, here is how the GNU make jobserver implementation works today. Below I will discuss some of the more hairy details, as well as describe some of the alternatives we considered and dismissed.
>
>1. The user invokes make with the -j N option, specifying parallel builds with at most N concurrent jobs.
>2. GNU make creates a pipe, and writes N-1 tokens into the pipe.
>  * A token is just a one-byte character.
>  * All tokens are identical.
>  * We write only N-1 tokens because one is considered used up by this top-level instance of make.

So yes, `with jobserver_job()` does acquire one of the tokens, but this token is assumed to be taken by the subsequent top-level call to `Make`.

What I said before, however, about the `cmake` call not being blocked was incorrect. The current implementation will prevent `cmake` from being run until one of the jobserver tokens is released.

**Comment by wjwwood** [comment] 2015-04-21 22:54
> In the line that you quoted "these jobs" refers to the -p, --parallel-packages, -j, and --jobs options mentioned in the previous pragraph. These options aren't passed unless you disable the jobserver with --no-jobserver. By default, the options passed to make when using the jobserver are those generated by make_jobserver.jobserver_arguments().

Yes, you're right, that makes sense to me now. Thank you.

> So yes, with jobserver_job() does acquire one of the tokens, but this token is assumed to be taken by the subsequent top-level call to Make.

So catkin build takes a token out of the job server on its behalf?

This is what I was getting at with my comment:

> It's also not clear to me how -p2 -j4 would result in to two jobs with two instances of make running in the equivalent to make -j2.

I wasn't thinking about equally distributing the jobs between make instances, I was trying to point out that if `with jobserver_job()` takes a token and there are two executors running, then the total available tokens for the leaf `make` instances is now two. I didn't know that the first call to `make`, even though it gets `--jobserver-fds=... -j`, would need a token taken out for it by catkin build. The way I read the description, that you keep linking to, it only passes `N - 1` tokens to its children iff it is invoked with `-j N` and no job server pipe was given to it as an option, but maybe I'm misunderstanding that point. I would have expected `make` to first take a token for itself from the file descriptor's given with `--jobserver-fds` and then let its children do the same.

So, if I'm wrong about the above paragraph this doesn't matter. But if I'm not then I would ask, why do we need the `with jobserver_job()` context?

If we do need it (I was wrong above), then we need to consider its impact on the running of CMake, which is where it comes back around to this issue, which is how `-j` and `-p` interact with each other. I'm suggesting that `-p` is already limited to `-j`, such that `-p` being greater than `-j` will always result in instances of `-p` type jobs being starved (even the cmake part). The confusing part about this is that they show up as started and running in the status and their build time is accumulating.

So if we want to block the run of CMake, and other non-make parts of jobs, based on available jobserver tokens, then it should be reflected in the UI. If not, then we have to consider how we can narrow the scope of the `with jobserver_job()` context. Maybe we could wrap any subprocess calls specifically to `make` in the context, but avoid wrapping the entire job.

Either way, thank you for helping me understand the design of the implementation.

**Comment by jbohren** [comment] 2015-04-22 01:32
Since CMake jobs can be expensive, it's probably good to keep them guarded by the jobserver.

So either we enforce `p≤j` or we modify the CLI status display.

I like the former, personally. So if the user specifies a `p` value greater than the `j` value, the `p` value will be reduced to the `j` value, and a warning week be displayed in the build summary.

**Comment by jbohren** [comment] 2016-01-20 02:21
In #249, the new execution pipeline enforces that there are never more packages being built than there are jobserver workers available.

**Closed by jbohren** 2016-01-20 02:21 UTC
Labels: enhancement
