### ISSUE TITLE
catkin build with linked develspace and install: true causes source devel/setup.bash to not work

### ISSUE THREAD

**Issue by shuhaowu** [catkin/catkin_tools#674] opened 2021-04-10 22:25 UTC
### System Info

* Operating System: `Linux starfruit 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux` (actually running inside a customized `osrf/ros:noetic-desktop-full-focal` docker container)
* Python Version: `Python 3.8.2`
* Version of catkin_tools: `0.5.0` 
* ROS Distro: `noetic`

### Build / Run Issue

* [x] Works with `catkin_make`
* [x] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`

So I have seen #376 and I have a very similar issue still, with a slightly different config. It's entirely possible that I'm using develspace and installspace incorrectly. I actually forked the example repo from that issue here: https://github.com/shuhaowu/catkin_tools_test_ws

The difference is that the [default profile has `install: true`](https://github.com/shuhaowu/catkin_tools_test_ws/blob/master/.catkin_tools/profiles/default/config.yaml), which in my understanding would generate an installspace that I can then tarball around. My understanding is that this config would also generate a develspace, and if I `source devel/setup.bash`, then I be able to run the packages I'm building locally. 

Except, this is not happening:

```
catkin build --profile default
. devel/setup.sh
rosrun py_dummy_pkg dummy.py
```

This gives: `[rospack] Error: package 'py_dummy_pkg' not found`, like the original author.

If we set `install: false`, then the package can be found and used.

### Expected Behavior

I expect that `source devel/setup.bash` would setup the packages for development, despite `install: true`. Is this the wrong expectation?

### Workaround

Create a second profile that does `install: true`, separate from the default profile with install = false. I also put all the spaces into a subfolder so things don't collide:

```
build_space: install/build
devel_space: install/devel
install_space: install/install
```

**Comment by timonegk** [comment] 2021-04-11 21:56
I cannot reproduce your problem. Could you run `echo $ROS_PACKAGE_PATH` before and after the `. devel/setup.sh` line and print your results?
Also, the solution to #376 was to source `setup.bash` instead of `setup.sh`. Could you try that (assuming your shell is bash)?

**Comment by enricovillagrossi** [comment] 2021-06-22 08:39
Currently I'm facing the same problem, is there any official fix?
It doesn't work if I source `setup.bash` file.

**Comment by timonegk** [comment] 2021-07-05 21:00
Could you give me the output of `echo $ROS_PACKAGE_PATH` before and after you source the setup file?

**Comment by enricovillagrossi** [comment] 2021-07-08 07:21
The result was always `/opt/ros/noetic/share` before and after sourcing the setup file. In my case, the problem disappeared when I reinstalled ROS (not trying to fix this problem but for other reasons).

**Comment by timonegk** [comment] 2021-07-13 11:28
Okay, I can now reproduce the problem, there previously was a problem on my side. The issue indeed seems to be that a linked devel space cannot be sourced when an install space is present. So the “official fix” would be to source the install space instead. For the isolated devel space, there is an error message when sourcing the devel space:
```
Error: This workspace was built with the '--install' option.
       You should source the setup files in the install space instead.
       Your environment has not been changed.
```
For the merged devel space, sourcing the devel space works even when an install space is present. I am not entirely sure why the behavior differs for the different devel space layouts and what the behavior for the linked devel space should be, but I will look into it.

**Comment by ajg3** [comment] 2021-08-06 17:02
I just want to comment that this is still a thing in `catkin_tools`.

```bash
catkin_tools 0.7.1 (C) 2014-2021 Open Source Robotics Foundation
catkin_tools is released under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
---
Using Python 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```

**Comment by TheDelus** [comment] 2022-03-29 10:27
> For the merged devel space, sourcing the devel space works even when an install space is present. I am not entirely sure why the behavior differs for the different devel space layouts and what the behavior for the linked devel space should be, but I will look into it.

@timonegk did you had the change to look into it? It´s quite anoying that one can not build with linked devel space AND install the package

**Comment by timonegk** [comment] 2022-04-19 13:27
Sorry it took so long. I added a patch in #725. The issue was that there is a `.catkin` file in the `devel` folder that is used to generate `ROS_PACKAGE_PATH` and it was only generated when not installing. Could you test the patch and look if it resolves the problem for you as well? You can install it directly with pip via `pip install git+https://github.com/catkin/catkin_tools@fix_devel_install`

**Closed** 2022-07-19 16:32 UTC
