### ISSUE TITLE
build: option to show compiler warnings

### ISSUE THREAD

**Issue by roehling** [catkin/catkin_tools#301] opened 2016-03-09 08:49 UTC
It would be really helpful if `build` had an option to show all compiler warnings after the build, even if the build was successful.

**Comment by wjwwood** [comment] 2016-03-09 18:30
You mean so it would summarize build warnings for each package after the build has completed? At least on the master branch, warnings are printed out as they are encountered, e.g.:

```
Starting  >>> pcl_ros
_________________________________________________________________________________________________________________________________________________________________________________
Warnings   << pcl_ros:check /Users/william/velodyne_ws/.catkin_tools/default/logs/pcl_ros/build.check.003.log
** WARNING ** io features related to openni will be disabled
** WARNING ** io features related to openni2 will be disabled
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
** WARNING ** visualization features related to openni will be disabled
** WARNING ** visualization features related to openni2 will be disabled
** WARNING ** apps features related to openni will be disabled
CMake Warning (dev) at CMakeLists.txt:82 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "pcl_ros_generate_messages_cpp" of target
  "pcl_ros_tf" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

cd /Users/william/velodyne_ws/build/pcl_ros; catkin build --get-env pcl_ros | catkin env -si  /usr/bin/make cmake_check_build_system; cd -
.................................................................................................................................................................................
Finished  <<< pcl_ros                      [ 10.5 seconds ]
```

If the later, this is probably a duplicate of https://github.com/catkin/catkin_tools/issues/1

**Comment by jbohren** [comment] 2016-03-09 18:33
@roehling it was so helpful that we added that and such functionality is in master! See #249 it should be released in the next couple of weeks.

**Closed by jbohren** 2016-03-09 18:33 UTC

**Comment by roehling** [comment] 2016-03-09 20:01
@jbohren @wjwwood Thanks! :+1:
