### ISSUE TITLE
Blank lines in output when using docker in GitHub Actions

### ISSUE THREAD

**Issue by MatthijsBurgh** [catkin/catkin_tools#643] opened 2021-01-26 10:31 UTC
### System Info

* Operating System: At least Ubuntu 16 & 18
* Python Version: `python 2.7`
* Version of catkin_tools: `(debian) python-catkin-tools all 0.6.1-1`
* ROS Distro: At least Kinetic & Melodic

### Expected Behavior

When using `catkin tools` in a docker in GitHub Actions, blank lines are captured in the output. It happens both with our own [CI implementation](https://github.com/tue-robotics/geolib2/runs/1652534174?check_suite_focus=true#step:2:2376) as with [Industrial CI](https://github.com/ros-industrial/industrial_ci/runs/1765908411?check_suite_focus=true#step:3:867). It doesn't happen on [Travis CI](https://travis-ci.com/github/tue-robotics/node_alive/jobs/472191820#L554) (Also in Industrial CI it doesn't happen on Travis)

It also happens with our own CI implementation in [azure pipelines](https://dev.azure.com/tue-robotics/tue-robotics/_build/results?buildId=2064&view=logs&j=bdc95d2f-3e6c-50fc-57a9-b190e67ee9d9&t=941fa5a7-f740-50e0-ec0e-e27f38f78852&l=61) (Uses the same scripts as GitHub Actions and Travis CI)

### Responsibility

I do understand that this isn't fully your responsibility as it doesn't show these empty lines on my local machine and Travis, but I really have no idea where to look for the cause and/or solution. And as it affects many people, I hope you do want to and are able to help to resolve this issue.

**Comment by MatthijsBurgh** [comment] 2021-01-26 10:35
This seems to be already discussed in https://github.com/ros-industrial/industrial_ci/pull/437#issuecomment-559177216. There seems to be a possible fix ready in #587

**Comment by MatthijsBurgh** [comment] 2021-01-26 20:07
#587 only removes the blank lines catkin logs, not the cmake/make logs

**Comment by MatthijsBurgh** [comment] 2021-01-26 21:13
The lines coming from (c)make are going into the `wide_log` here: https://github.com/catkin/catkin_tools/blob/0.6.x/catkin_tools/execution/controllers.py#L729. Theses lines end on `\r\n`.

Where should the lines be stripped from the unwanted line ending and be fitted with the correct line ending? As that doesn't happen before getting from `wide_log` to the print  at https://github.com/catkin/catkin_tools/blob/0.6.x/catkin_tools/common.py#L387 (Indepent from which wide_log_fn is used)

**Comment by MatthijsBurgh** [comment] 2021-01-27 10:20
If you check the raw log of travis, it also contains these blank lines. These are just not show in the normal output.

**Comment by asherikov** [comment] 2021-02-19 17:57
This is an old glitch, it happens when you redirect output to a file instead of a terminal. If I am not mistaken this is the offending line -> https://github.com/catkin/catkin_tools/blob/0.6.x/catkin_tools/execution/controllers.py#L767, the terminal width cannot be detected properly when redirected to a file, and some default (80?) value is used. 
Currently I simply filter all catkin output with sed ;)

**Comment by MatthijsBurgh** [comment] 2021-02-19 18:33
@asherikov as described above #587 fixes a part of the issue, the rest is in my other comment above https://github.com/catkin/catkin_tools/issues/643#issuecomment-767831421. I will have to take a look again to determine a good point to strip the unwanted line ending and add the correct one.

**Comment by asherikov** [comment] 2021-02-21 13:31
sorry, I didn't read carefully and was vague, so here is my point:
- catkin output is buggy when redirected to a file -- this is the reason why the problems are observed in CI, but not when running catkin in a terminal, issues can be reproduced locally by redirecting the output.
- in my case the main problem is not empty lines, but rather lines filled with 'terminal-width' number of spaces, generated by the line I linked above as far as I understand.
- I believe we are having the same problem since the terminal width may be detected as zero in your case, so that you get empty lines.

**Comment by timonegk** [comment] 2021-02-21 13:59
Could you test with `--no-status`?

**Comment by asherikov** [comment] 2021-02-21 14:38
`--no-status` has no effect, but removing `--interleave-output` helps. It looks like interleaved output is not used in the CI jobs linked above, so the issues are probably unrelated.

**Comment by MatthijsBurgh** [comment] 2021-02-23 10:36
We run `catkin run_tests --this --no-deps -DCATKIN_ENABLE_TESTING=ON` so it happens with `--no-status`

**Comment by timonegk** [comment] 2021-03-19 14:37
Closed in #666.

**Closed by timonegk** 2021-03-19 14:37 UTC
