### ISSUE TITLE
setup scripts don't work as expected for linked devel layout

### ISSUE THREAD

**Issue by dominiquehunziker** [catkin/catkin_tools#376] opened 2016-05-26 16:11 UTC
### System Info
- Operating System: Linux RR01 3.13.0-86-generic #131-Ubuntu SMP Thu May 12 23:33:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Python Version: Python 2.7.6
- Version of catkin_tools: 4f5fa9dc318f2245dd249a738c44cd3e9a317ad3
- ROS Distro: indigo
- Shell: `/bin/bash`
### Build / Run Issue

The generated setup scripts don't work as expected for the linked devel space layout.

Sample workspace: https://github.com/dominiquehunziker/catkin_tools_test_ws

For the configuration

```
Devel Space Layout:          linked
Install Space Layout:        None
```

`devel/setup.sh` doesn't configure the environment correctly.

``` bash
. /opt/ros/indigo/setup.sh
catkin clean -y
catkin config --link-devel
catkin build
. devel/setup.sh
rosrun py_dummy_pkg dummy.py
```

gives

```
[rospack] Error: package 'py_dummy_pkg' not found
```

On the other hand

``` bash
. devel/setup.bash
rosrun py_dummy_pkg dummy.py
```

is able to find and execute the node.

Doing the same with a merged devel layout

```
Devel Space Layout:          merged
Install Space Layout:        None
```

works as expected:

``` bash
. /opt/ros/indigo/setup.sh
catkin clean -y
catkin config --merge-devel
catkin build
. devel/setup.sh
rosrun py_dummy_pkg dummy.py
```

**Comment by cyberguy42** [comment] 2017-04-28 21:39
I have encountered a similar situation. In short, sourcing devel/setup.sh does not do the same thing as sourcing devel/setup.bash.

I am using Indigo with Ubuntu 14.04. I installed catkin_tools using apt-get according to this [tutorial](http://catkin-tools.readthedocs.io/en/latest/installing.html). I have confirmed that I have the most recent version.

I used rosinstall_generator along with wstool to download the sources for the variant 'robot'. I followed this [tutorial](http://wiki.ros.org/indigo/Installation/Source) with these alterations: I moved the catkin package along with the few pure cmake packages from my main catkin workspace (WORKSPACE) into a separate one (ISOLATED) and then ran `./src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release`.

Next, in WORKSPACE, I created and configured my catkin workspace:

```
---------------------------------------------------------------
Profile:                     default
Extending:        [explicit] <ISOLATED>/catkin_isolated_ws/install_isolated
Workspace:                   <WORKSPACE>
---------------------------------------------------------------
Source Space:       [exists] <WORKSPACE>/src
Log Space:          [exists] <WORKSPACE>/logs
Build Space:        [exists] <WORKSPACE>/build
Devel Space:        [exists] <WORKSPACE>/devel
Install Space:      [unused] <WORKSPACE>/install
DESTDIR:            [unused] None
---------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
---------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    False
Cache Job Environments:      True
---------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
---------------------------------------------------------------
Workspace configuration appears valid.

```

I ran `catkin build`, and everything compiled successfully.

After sourcing setup.sh, I tried using rospack, rosrun, etc. and always got the message  `command not found`. Having seen this issue, I tried sourcing setup.bash, and they worked. Next I looked at my $PATH, and found that setup.bash adds `WORKSPACE/devel/bin` to the front of my path, while setup.sh adds `WORKSPACE/devel/.private/catkin/bin`. The former works, the latter does not.

I have yet another workspace (LEGACY) that extends `/opt/ros/indigo`. In this case, rosrun, rospack, etc, work fine, but even after sourcing LEGACY/devel/setup.sh, they do not 'see' any of the packages in LEGACY. However, if I source LEGACY/devel/setup.bash, those packages are seen.

If I have done anything incorrectly, please let me know. Otherwise, this would appear to be a significant bug.

**Comment by wjwwood** [comment] 2017-06-06 00:50
Sorry, I haven't had time to get to this sooner.

Is there a reason you guys are sourcing the `.sh` file rather than the `.bash` or `.zsh`? I just tried to reproduce this and I can if I source the `.sh` but not when I source the `.bash`.

I guess there is a special `setup.bash` and `setup.zsh` for a linked devel space, but there was no specialization done for `setup.sh`, but I don't know that for sure. I'd have to dig into the implementation that @jbohren originally did for that.

For now, I'd recommend you just use `.bash` or .`zsh` as that's the expected thing to do anyways imo.

**Comment by wjwwood** [comment] 2017-06-06 00:53
Actually just looking a bit more, it looks like there is no specialization within the those files for the linked develspace. Anyways I still just recommend the workaround for now.

**Comment by cyberguy42** [comment] 2017-06-07 16:02
The workaround fully resolves the issue for me.

The reason I was sourcing the `.sh` file is because that was what I always did with `catkin_make`; it never occurred to me that it might make a difference until I saw this issue. Perhaps a warning could be added to the [migration guide](https://github.com/catkin/catkin_tools/blob/master/docs/migration.rst)?

**Comment by mikepurvis** [comment] 2017-06-07 16:28
The bash wrapper uses `BASH_SOURCE` to figure out where it is:

```
_CATKIN_SETUP_DIR=$(builtin cd "`dirname "${BASH_SOURCE[0]}"`" > /dev/null && pwd)
. "$_CATKIN_SETUP_DIR/setup.sh"
```

If you don't use the wrapper, then `setup.sh` relies on the location it was given at configuration time— which is going to be wrong in the case where you've gone through a symlink from elsewhere.

**Comment by wjwwood** [comment] 2017-07-18 00:18
> Perhaps a warning could be added to the migration guide?

Sounds fine to me, if anyone has time to add it that would be great. I'm happy to merge it or review it.

**Comment by wjwwood** [comment] 2017-07-18 00:18
I'm going to close this in the mean time.

**Closed by wjwwood** 2017-07-18 00:18 UTC

**Comment by mintar** [comment] 2023-02-02 14:35
Why was this bug closed? It's still there (after more than 5 years), and I just lost a whole day debugging it!

> Is there a reason you guys are sourcing the .sh file rather than the .bash or .zsh?

Yes, I'm trying to use this in a Github Actions workflow, which is neither bash nor zsh. Of course there are ways to work around (wrap everything in a `/usr/bin/bash -c "[...]"`, use the merged layout, or scrap catkin_tools and use catkin_make instead). But you have to figure out that `catkin_tools` generates a broken `setup.sh` first, which is annoying, especially because when you try to reproduce the bug locally, it doesn't show up if your local shell is bash or zsh and you source the corresponding setup.bash or setup.zsh out of habit.

**Comment by gavanderhoorn** [comment] 2023-02-02 14:43
> I'm trying to use this in a Github Actions workflow, which is neither bash nor zsh. Of course there are ways to work around (wrap everything in a `/usr/bin/bash -c "[...]"`

more of a work-around, but you can actually [configure an alternative default shell](https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs) for GHA to use (including Bash).
