### ISSUE TITLE
Catkin ignores packaes with AMENT_IGNORE?

### ISSUE THREAD

**Issue by Levi-Armstrong** [catkin/catkin_tools#535] opened 2019-02-13 18:49 UTC
### System Info

* Operating System: Linux swri 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 2.7.12
* Version of catkin_tools: `catkin --version` OR *Git revision*
* ROS Distro: kinetic

### Steps to Reproduce the Issue

Add a file named AMENT_IGNORE to package directory and then build.

**Comment by dirk-thomas** [comment] 2019-02-13 18:59
That is the intended behavior. See ros-infrastructure/catkin_pkg#226 which provides the functionality.

**Comment by Levi-Armstrong** [comment] 2019-02-13 19:15
Is it possible to have something as described. I have several packages that have the potential to be build using ros1 and ros2 with some modification. I had planned on putting AMENT_IGNORE in the ros1 folder and CATKIN_IGNORE in the ros2 folder but it sounds like this is not a possible solution.  Is there a alternative solution?

package
- include
- src
- ros1
  - CMakeLists.txt
  - package.xml
- ros2
  -CMakeLists.txt
  - package.xml

**Comment by gavanderhoorn** [comment] 2019-02-13 19:19
Use the blacklist/whitelist feature of `catkin_tools`?

**Comment by Levi-Armstrong** [comment] 2019-02-13 19:22
That could work but right now I the same package name in both package.xml.

**Comment by gavanderhoorn** [comment] 2019-02-13 19:33
In the same workspace?

---

Edit: oh, I just now see the package layout. That's a strange package layout: would it not make more sense to take the common files out and host them in either (what would become) a system dependency or separate ROS pkg and then have the ROS 1 and ROS 2 pkg depend on that?

That would solve this I believe (as the ROS 1 and ROS 2 pkgs would then not be in the same workspace at the same time).

**Comment by dirk-thomas** [comment] 2019-02-13 19:56
The `include` and `src` directories are not even part of any package since they are above the directories which contain the `package.xml` / `CMakeLists.txt` files. That layout doesn't make any sense.

Maybe take a step back and describe what your use case is / what you want to achieve.

**Comment by Levi-Armstrong** [comment] 2019-02-13 19:56
What is the preferred process for releasing as system dependency; can I still leverage the ros build farm? In the past I have used launchpad.net with a custom ppa, but I was planning on leveraging the ros release process.

**Comment by Levi-Armstrong** [comment] 2019-02-13 20:00
The `include` and `src` don't have to be child directories. You can provide relative paths in the CMakeLists.txt and everything works as expected. Also this is just a test to determine the possibility of release a single set of source code for both ROS1 and ROS2 without having to create two separate branches just for the purpose of release ROS1 or ROS2.

**Comment by dirk-thomas** [comment] 2019-02-13 20:08
> You can provide relative paths in the CMakeLists.txt and everything works as expected

This would fail if you try to release your repository. Simply because a package is defined to be the recursive content starting from a `package.xml` file. E.g. when `bloom` extracts packages from a repo into separate branches in the release your parent directory content won't be available.

**Comment by Levi-Armstrong** [comment] 2019-02-13 20:08
I have a few packages that are basically wrappers around system dependencies providing a common interface for collision checking, kinematics, environment and with the use of console_bridge I am able to build them on both ROS1 and ROS2 independently leveraging different CMakeLists.txt and package.xml.

**Comment by Levi-Armstrong** [comment] 2019-02-13 20:11
> This would fail if you try to release your repository. Simply because a package is defined to be the recursive content starting from a `package.xml` file. E.g. when `bloom` extracts packages from a repo into separate branches in the release your parent directory content won't be available.

Would symbolically linking the directories under the ROS1 and ROS2 directories solve this issue?

**Comment by gavanderhoorn** [comment] 2019-02-13 20:17
Getting off-topic here for this issue, but: would it make sense to version the ROS 2 and ROS 1 together? They're probably going to go in different directions, due to changes in dependencies.

If it doesn't make sense, could/should they not be hosted in different repositories?

The common part would be hosted in yet another repository.

**Comment by Levi-Armstrong** [comment] 2019-02-13 20:25
> Getting off-topic here for this issue, but: would it make sense to version the ROS 2 and ROS 1 together? They're probably going to go in different directions, due to changes in dependencies.

I agree, It is purely to reduce the maintenance burden in the short term. Right now it would not be an issue so was hoping to cross that road later. 

It is probably best to continue discussion [here](https://github.com/ros-industrial-consortium/tesseract/issues/43)

**Comment by dirk-thomas** [comment] 2019-02-13 21:53
> ... leveraging different CMakeLists.txt and package.xml.

If all it takes is differences in CMake and the manifest you should be able to have everything in a single ROS package. In CMake you could simply have two conditional blocks - one for ROS 1 and one for ROS 2 - with the same content you have in two separate files. And the manifest could use the `condition` attribute on the dependency tags to scope them to one of the ROS versions.

**Comment by Levi-Armstrong** [comment] 2019-02-13 22:18
Oh, I was not aware of the condition attribute in the manifest which should solve the issue. Thank you all for the help and I will post and update once I get it working.

**Comment by Levi-Armstrong** [comment] 2019-02-13 22:47
Just for anyone else that runs into this make sure to change `<package format="2">` to `<package format="3">` to leverage the condition attribute.

**Comment by timonegk** [comment] 2021-02-11 14:18
Since ignoring packages with `AMENT_IGNORE` is intended behavior and the condition attribute can be used to handle differences in `package.xml`, I am closing this issue.

**Closed by timonegk** 2021-02-11 14:18 UTC
Labels: question
